In [1]:
!pip install gym

Defaulting to user installation because normal site-packages is not writeable


In [2]:
from gym import Env
from gym.spaces import Discrete, Box
import numpy as np
from enum import Enum

In [154]:
def getPossibleActions(depth=4):
    state = np.arange(9).reshape((3,3))
    
    possibleActions = getPossibleActionsSub(state, [], depth)
    
    possibleActions = set(map(lambda x: tuple(sorted(x)), possibleActions ))
    possibleActions = list(possibleActions)
    
    
    return possibleActions
    
def getPossibleActionsSub(state, used, depth):
    if depth == 0:
        return np.asarray([])
    
    possibleActions = []
    
    for i in range(len(statetmp)):
        for j in range(len(statetmp[0])):
            
            usedtmp = used.copy()
            
            if not statetmp[i][j] in usedtmp:
                neighbors = getNeighbors(statetmp, i, j)
                for neighbor in neighbors:
                    if neighbor >= 0 and  not (neighbor, statetmp[i][j]) in possibleActions and not neighbor in usedtmp:
                        possibleActions.append((statetmp[i][j], neighbor))
                        usedtmp.append(statetmp[i][j])
                        usedtmp.append(neighbor)
 
                        for action in getPossibleActionsSub(state, usedtmp, depth-1):
                            if type(action) == tuple:
                                possibleActions.append([(statetmp[i][j], neighbor), action])
                            elif type(action) == list:
                                action.append((statetmp[i][j], neighbor))
                                possibleActions.append(action)
                                
        
    return possibleActions

testing if possibleActions is correct

In [100]:
state = np.zeros((10,3,3))
for i in range(len(state)):
    state[i] = np.arange(9).reshape((3,3))

#print(state)

possibleActions = getPossibleActions()
#print(len(possibleActions))
#print(possibleActions)

a = possibleActions[0]



print(type(a[0]))

statetmp = np.arange(9).reshape((3,3))

swap(state, a[0])

print(state[0])

#for i in range(len(possibleActions)):
#output = set(map(lambda x: tuple(sorted(x)),possibleActions))

#print(len(output))

<class 'tuple'>
[[0. 1. 5.]
 [3. 4. 2.]
 [6. 7. 8.]]


Discrete(130)

In [ ]:
possibleActions = []

statetmp = np.arange(9).reshape((3,3))

for i in range(len(statetmp[0])):
    for j in range(len(statetmp[0][0])):
        neighbors = getNeighbors(statetmp, i, j)
        for neighbor in neighbors:
            used = []
            if neighbor >= 0:#and not [(neighbor, statetmp[i][j])] in possibleActions:
                possibleActions.append([statetmp[i][j], neighbor])
                used.append(statetmp[i][j])
                used.append(neighbor)
                
                
            
            for x in range(len(statetmp[0])):
                for y in range(len(statetmp[0][0])):
                    tmp = used
                    qubit = statetmp[x][y]
                    if not qubit in tmp:
                        if neighbor >= 0:# and not [(neighbor, statetmp[i][j])] in possibleActions:
                            possibleActions.append([statetmp[i][j], neighbor])
                            tmp.append(statetmp[i][j])
                            tmp.append(neighbor)

            
                
print(possibleActions) 
print(len(possibleActions))

In [98]:
def swap(state, actions):
    if type(actions[0]) != tuple:
        actions = [actions]
    for action in actions:
        if action == (0, 1) or action == (1, 0): 
            row0, col0, row1, col1 = 0, 0, 0, 1
        elif action == (1, 2) or action == (2, 1):  
            row0, col0, row1, col1 = 0, 1, 0, 2
        elif action == (0, 3) or action == (3, 0): 
            row0, col0, row1, col1 = 0, 0, 1, 0
        elif action == (4, 1) or action == (1, 4): 
            row0, col0, row1, col1 = 0, 0, 1, 1
        elif action == (2, 5) or action == (5, 2): 
            row0, col0, row1, col1 = 0, 2, 1, 2
        elif action == (3, 4) or action == (4, 3): 
            row0, col0, row1, col1 = 1, 0, 1, 1
        elif action == (4, 5) or action == (5, 4): 
            row0, col0, row1, col1 = 1, 1, 1, 2
        elif action == (3, 6) or action == (6, 3): 
            row0, col0, row1, col1 = 1, 0, 2, 0
        elif action == (4, 7) or action == (7, 4): 
            row0, col0, row1, col1 = 1, 0, 2, 1
        elif action == (5, 8) or action == (8, 5): 
            row0, col0, row1, col1 = 1, 0, 2, 2
        elif action == (7, 6) or action == (6, 7): 
            row0, col0, row1, col1 = 2, 0, 2, 1
        elif action == (7, 8) or action == (8, 7): 
            row0, col0, row1, col1 = 2, 1, 2, 2

        #swap for all future states
        for i in range(len(state)):
            state[i][row0][col0], state[i][row1][col1] = state[i][row1][col1], state[i][row0][col0]

In [79]:
def getNeighbors(state, row_number, column_number):
    a = [[state[i][j] if  i >= 0 and i < len(state) and j >= 0 and j < len(state[0]) else -1
                    for j in range(column_number-1, column_number+2)]
                        for i in range(row_number-1, row_number+2)]
    return [a[0][1], a[1][0], a[1][2], a[2][1]]

In [49]:
#                      [[1,0,0],
#Takes in a state like  [1,0,2], and checks if the corresonding numbers are neighbors
#                       [2,0,0]]

def isExecutableState(state):
    for row in range(len(state[0])):
        for col in range(len(state[0][0])):
            if state[0][row][col] > 0:
                if not state[0][row][col] in getNeighbors(state[0], row, col):
                    return False
    #return bool
    return True

testing of the functions isValidState and swap

In [ ]:
arr = np.zeros((10,3,3), dtype=int)
arr[0][0][1] = 1
arr[0][0][2] = 2
arr[0][1][1] = 1
arr[0][1][2] = 2
arr[1] = arr[0]

print(arr[0])
print(arr[1])
print(isExecutableState(arr))

swap(arr, 1)
print(arr[0])
print(arr[1])
print(isExecutableState(arr))

In [50]:
def makeState():
    state = np.zeros((10,3,3))
    for i in range(len(state)):
        random = np.random.choice([3,5,7,9])
        matrix = np.ceil(np.arange(random)/2)
        matrix = np.append(matrix, np.zeros(9-random)).reshape((3,3))
        np.random.shuffle(matrix)
        state[i] = matrix
    return state

Test function makeState

In [ ]:
makeState()

In [159]:
#Our enviorment
class Kvant(Env):
    def __init__(self):
        #Actions we can take
        #self.action_space = Discrete(130)
        self.action_space = Discrete(12)
        #
        self.observation_space = Box(low=np.zeros((10,3,3), dtype=int), high=np.zeros((10,3,3), dtype=int)+4)
        
        #The start state
        self.state = makeState()
        
        #possible actions
        #self.possibleActions = getPossibleActions()
        self.possibleActions = getPossibleActions(1)
        
        #timesteps
        self.timeSteps = 100
        
    def step(self, action):
        
        actions = self.possibleActions[action]
        #print(actions)
        #for a in actions:
        swap(self.state, a)
        
        self.time_steps -= 1
        
        if isExecutableState(self.state):
            reward = 1
        elif self.time_steps <= 0:
            reward = -1
        else:
            reward = -1
            
    
        if isExecutableState(self.state) or self.time_steps <= 0:
            done = True
        else:
            done = False
        info = {}
        
        return self.state, reward, done, info
        
    def render(self):
        pass
    
    def reset(self):
        self.state = makeState()
        self.time_steps = 100
        return self.state

In [160]:
env = Kvant()

In [162]:
episodes = 1000
scores = []
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0 
    
    while not done:
        #env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    scores.append(score)

In [164]:
for i in range(-100, 2):
    print('Number of', i, 'is', scores.count(i))

Number of -100 is 513
Number of -99 is 0
Number of -98 is 0
Number of -97 is 0
Number of -96 is 0
Number of -95 is 0
Number of -94 is 0
Number of -93 is 0
Number of -92 is 0
Number of -91 is 0
Number of -90 is 0
Number of -89 is 0
Number of -88 is 0
Number of -87 is 0
Number of -86 is 0
Number of -85 is 0
Number of -84 is 0
Number of -83 is 0
Number of -82 is 0
Number of -81 is 0
Number of -80 is 0
Number of -79 is 0
Number of -78 is 0
Number of -77 is 0
Number of -76 is 0
Number of -75 is 0
Number of -74 is 0
Number of -73 is 0
Number of -72 is 0
Number of -71 is 0
Number of -70 is 0
Number of -69 is 0
Number of -68 is 0
Number of -67 is 0
Number of -66 is 0
Number of -65 is 0
Number of -64 is 0
Number of -63 is 0
Number of -62 is 0
Number of -61 is 0
Number of -60 is 0
Number of -59 is 0
Number of -58 is 0
Number of -57 is 0
Number of -56 is 0
Number of -55 is 0
Number of -54 is 0
Number of -53 is 0
Number of -52 is 0
Number of -51 is 0
Number of -50 is 0
Number of -49 is 0
Number of